[package]
name = "envboxes"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Vijay Ramanathan"]
license = "MIT"
description = "Math Environment boxes for theorems, definitions and more."
# repository = "https://github.com/shadowmachete"
